apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-microservice-deployment
  namespace: dev
  labels:
    app: orders-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-microservice
  template:
    metadata:
      labels:
        app: orders-microservice
    spec:
      containers:
        - name: orders-microservice
          image: scottazurecontainerregistry.azurecr.io/orders-microservice:__TAG__
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dev-config
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RabbitMqUsername

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RabbitMqPassword
