apiVersion: v1
kind: Service
metadata:
  name: orders-microservice
  namespace: prod
spec:
  selector:
    app: orders-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
