apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-config
  namespace: staging
data:
  # MongoDB host, port, and database name (non-sensitive)
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: OrdersDatabase

  # Template for your MongoDB connection
  ConnectionStrings__MongoDB: |
    mongodb://$MONGO_HOST:$MONGO_PORT

  # Other service endpoints
  UsersMicroservicePort: "8080"
  UsersMicroserviceName: apigateway
  ProductsMicroservicePort: "8080"
  ProductsMicroserviceName: apigateway

  # Redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"

  # RabbitMQ (non-sensitive bits)
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_PRODUCTS_EXCHANGE: products.exchange
  RABBITMQ_USERS_EXCHANGE: users.exchange
